name: Remote Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: Genesys225/cloudflared-service-token-ssh-proxy@V1
        with:
          HOST: pi4b.fuckgfw.store
          PORT: 22
          USER: chuck
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          KEY_TYPE: id_ed25519
          REMOTE_SHELL: 'zsh'
          COMMAND: |
            cd /home/chuck/code/hot-search
            git pull origin master
            docker compose down
            docker rmi hot-search:latest || true
            docker compose up -d
