name: Remote Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: and-fm/cloudflared-ssh-action@v3
        with:
          host: pi4b.fuckgfw.store
          port: 22
          username: chuck
          private_key_filename: ${{ secrets.SSH_PRIVATE_KEY_FILENAME }}
          private_key_value: ${{ secrets.SSH_PRIVATE_KEY_VALUE }}
          commands: |
            export https_proxy=http://127.0.0.1:1080 http_proxy=http://127.0.0.1:1080 all_proxy=socks5://127.0.0.1:1080
            cd /home/chuck/code/hot-search
            git pull origin master
            docker compose down
            docker rmi hot-search:latest || true
            docker compose up -d
